name: Build Driver
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: sudo apt install -y build-essential gcc-aarch64-linux-gnu
      - name: Kernel
        run: git clone --depth=1 https://github.com/LowTension/android_kernel_xiaomi_sm8475 kernel
      - name: Driver
        run: git clone --depth=1 https://github.com/morrownr/8812au-20210820 driver
      - name: Compile
        run: |
          cd driver
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- KSRC=$(pwd)/../kernel
      - name: Save
        uses: actions/upload-artifact@v3
        with:
          name: 8812au-ko
          path: driver/8812au.ko
